#! /bin/bash
# shellcheck disable=SC2086

set -o errexit

MD5_CMD=${MD5_CMD:-md5sum}
CACHE_KEY_PREFIX=${CACHE_KEY_PREFIX:-}

CACHE_ON_DIR=$1

if [[ ! "$CACHE_KEY_PREFIX" || ! "$CACHE_ON_DIR" ]]; then
  echo "cache_run: error: missing required input"
  exit 1
fi

CHK_SUM=$(find $CACHE_ON_DIR -type f -exec $MD5_CMD {} \; | $MD5_CMD | cut -f1 -d ' ')

echo "cache_get: calculated checksum on dir $CACHE_ON_DIR : $CHK_SUM"

if ! cachr exists "$CACHE_KEY_PREFIX/$CHK_SUM"; then
  echo "cache_get: error: expected cache key doesn't exists $CACHE_KEY_PREFIX/$CHK_SUM"
  exit 1
fi

echo "cache_get: getting key: $CACHE_KEY_PREFIX/$CHK_SUM"
cachr get "$CACHE_KEY_PREFIX/$CHK_SUM"
rm "$CHK_SUM"
