#! /bin/bash
# shellcheck disable=SC2086

set -o errexit

# shellcheck source=setup.sh
source setup.sh

CACHE_ON_DIR=$1

if [[ ! "$CACHE_KEY_PREFIX" || ! "$CACHE_ON_DIR" ]]; then
  echo "cache_run: error: missing required input"
  exit 1
fi

CHK_SUM=$(dir_md5_checksm $CACHE_ON_DIR $MD5_CMD)

echo "cache_get: calculated checksum on dir $CACHE_ON_DIR : $CHK_SUM"

if ! cachr exists "$CACHE_KEY_PREFIX/$CHK_SUM"; then
  echo "cache_get: error: expected cache key doesn't exists $CACHE_KEY_PREFIX/$CHK_SUM"
  exit 1
fi

echo "cache_get: getting key: $CACHE_KEY_PREFIX/$CHK_SUM"
cachr get "$CACHE_KEY_PREFIX/$CHK_SUM"
rm "$CHK_SUM"
