#! /bin/bash
# shellcheck disable=SC2086

set -o errexit

# shellcheck source=setup.sh
source setup.sh

CACHE_ON_DIR=${CACHE_ON_DIR:-}

# should be space separated
CACHE_OUT_DIRS=${CACHE_OUT_DIRS:-}

COMMAND=$1

if [[ ! "$COMMAND" || ! "$CACHE_KEY_PREFIX" || ! "$CACHE_ON_DIR" || ! "$CACHE_OUT_DIRS" ]]; then
  echo "cache_run: error: missing required input"
  exit 1
fi

CHK_SUM=$(dir_md5_checksm $CACHE_ON_DIR $MD5_CMD)

echo "cache_run: calculated checksum on dir $CACHE_ON_DIR : $CHK_SUM"

if cachr exists "$CACHE_KEY_PREFIX/$CHK_SUM"; then
  echo "cache_run: cache already exists! skipping..."
  exit 0
fi

echo "cache_run: checkout prev commit"
git checkout HEAD~1 > /dev/null

PREV_CHK_SUM=$(dir_md5_checksm $CACHE_ON_DIR $MD5_CMD)

echo "cache_run: getting cache: $PREV_CHK_SUM for commit: $(git rev-parse HEAD)"
cachr get "$CACHE_KEY_PREFIX/$PREV_CHK_SUM" || true

echo "cache_run: checkout current commit"
git checkout - > /dev/null

echo "cache_run: running command"
bash -c "$COMMAND"

echo "cache_run: saving cache to s3"
cachr save "$CACHE_KEY_PREFIX/$CHK_SUM" $CACHE_OUT_DIRS
